verbs = {
    "interesar": "to interest",
    "saber": "to know",
    "querer": "to want",
    "necesitar": "to need",
    "poder": "to be able to (can)",
    "deber": "to owe (must)",
    "ver": "to see",
    "ir": "to go",
    "comer": "to eat",
    "salir": "to go out",
    "bailar": "to dance",
    "ser": "to be (characteristic)",
    "estar": "to be (state)",
    "tener": "to have",
    "venir": "to come",
    "dormir": "to sleep",
    "hablar": "to speak",
    "decir": "to say/tell",
    "preguntar": "to ask",
    "llamar": "to call",
    "entender": "to understand",
    "pensar": "to think",
    "cocinar": "to cook",
    "poner": "to put",
    "esperar": "to wait/hope",
    "preferir": "to prefer",
    "intentar": "to attempt/to try",
    "comprar": "to buy",
    "vender": "to sell",
    "cambiar": "to change",
    "tomar": "to take",
    "vivir": "to live",
    "cenar": "to dine",
    "perder": "to lose",
    "terminar": "to end",
    "cansar": "to tire (out)",
    "creer": "to believe",
    "crear": "to create",
    "abrir": "to open",
    "cerrar": "to close",
    "doler": "to hurt",
    "llegar": "to arrive",
    "olvidar": "to forget",
    "sentar": "to sit",
    "callar": "to quiet",
    "elegir": "to choose",
    "seguir": "to follow",
    "volver": "to return",
    "dejar": "to leave",
    "contar": "to tell",
    "jurar": "to swear (promise)",
    "sentir": "to feel",
    "quemar": "to burn",
    "traer": "to bring",
}